server:
  port: 9000
  servlet:
    context-path: /web

Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111
    url: jdbc:mysql://localhost:3306/db_library?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*Mapper.xml






